import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os

# Set Page Config
st.set_page_config(page_title="YouTube Comment Analytics", layout="wide", page_icon="📊")

# --- DATA LOADING ---
@st.cache_data
def load_data():
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    data_path = os.path.join(base_dir, "data", "processed", "comments_processed.csv")
    if not os.path.exists(data_path):
        return None
    df = pd.read_csv(data_path)
    return df

df = load_data()

# --- HEADER ---
st.title("📹 YouTube Comment Analytics Dashboard")
st.markdown("Exploring audience sentiment, engagement, and linguistic trends.")

if df is None:
    st.error("Processed data not found. Please run the processing pipeline first.")
    st.stop()

# --- SIDEBAR FILTERS ---
st.sidebar.header("Filters")
selected_video = st.sidebar.selectbox("Filter by Video ID", ["All"] + list(df['video_id'].unique()))
selected_lang = st.sidebar.multiselect("Filter by Language", options=df['language'].unique(), default=df['language'].unique())

filtered_df = df.copy()
if selected_video != "All":
    filtered_df = filtered_df[filtered_df['video_id'] == selected_video]
filtered_df = filtered_df[filtered_df['language'].isin(selected_lang)]

# --- KEY METRICS ---
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Total Comments", len(filtered_df))
with col2:
    st.metric("Average Likes", round(filtered_df['like_count'].mean(), 2))
with col3:
    pos_count = len(filtered_df[filtered_df['sentiment_label'] == 'positive'])
    st.metric("Positive Comments", f"{pos_count} ({round(pos_count/len(filtered_df)*100, 1)}%)")
with col4:
    unique_authors = filtered_df['author'].nunique()
    st.metric("Unique Contributors", unique_authors)

st.divider()

# --- VISUALIZATIONS ---
row1_col1, row1_col2 = st.columns(2)

with row1_col1:
    st.subheader("Sentiment Distribution")
    sentiment_counts = filtered_df['sentiment_label'].value_counts()
    fig_sent = px.pie(
        names=sentiment_counts.index, 
        values=sentiment_counts.values,
        color=sentiment_counts.index,
        color_discrete_map={'positive': '#2ecc71', 'neutral': '#f1c40f', 'negative': '#e74c3c'},
        hole=0.4
    )
    st.plotly_chart(fig_sent, use_container_width=True)

with row1_col2:
    st.subheader("Top Languages")
    lang_counts = filtered_df['language'].value_counts().head(10)
    fig_lang = px.bar(
        x=lang_counts.index, 
        y=lang_counts.values,
        labels={'x': 'Language Code', 'y': 'Count'},
        color=lang_counts.values,
        color_continuous_scale="Viridis"
    )
    st.plotly_chart(fig_lang, use_container_width=True)

st.divider()

row2_col1, row2_col2 = st.columns(2)

with row2_col1:
    st.subheader("Engagement: Likes vs Sentiment")
    fig_scatter = px.scatter(
        filtered_df, 
        x='sentiment_score', 
        y='like_count',
        color='sentiment_label',
        hover_data=['clean_text'],
        size='char_count',
        opacity=0.6,
        color_discrete_map={'positive': '#2ecc71', 'neutral': '#f1c40f', 'negative': '#e74c3c'}
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

with row2_col2:
    st.subheader("Comment Length Distribution")
    fig_hist = px.histogram(
        filtered_df, 
        x='word_count', 
        nbins=30,
        color_discrete_sequence=['#3498db']
    )
    st.plotly_chart(fig_hist, use_container_width=True)

st.divider()

# --- TOP COMMENTS TABLE ---
st.subheader("Explore Comments")
sort_by = st.selectbox("Sort By", ["like_count", "sentiment_score", "word_count"], index=0)
st.dataframe(
    filtered_df[['author', 'like_count', 'sentiment_label', 'sentiment_score', 'language', 'clean_text']]
    .sort_values(by=sort_by, ascending=False)
    .head(50),
    use_container_width=True
)

st.markdown("---")
st.caption("Dashboard generated by Antigravity Dashboard Engine.")
